# docker-compose.yml (formato moderno - sin "version")
services:
  app:
    build: .
    image: movie-bff-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - movie-bff-postgres
    environment:
      - NODE_ENV=production

  movie-bff-postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moviebff
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # si quieres que Jenkins controle Docker local

volumes:
  postgres_data:
  jenkins_home:
