# Usage: Run this script from the repository root in PowerShell.
# It will prompt for your GitHub Personal Access Token (secure input), write it to `.env` and restart the Jenkins service using docker-compose.
# Notes:
# - This writes a plaintext token to `.env` so DO NOT commit that file.
# - You can also set the GIT_TOKEN environment variable yourself and skip this script.

Param()

function Convert-SecureStringToPlainText {
    param([System.Security.SecureString]$secureString)
    if (-not $secureString) { return '' }
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureString)
    try { [Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr) }
    finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
}

Write-Host "Enter GitHub Personal Access Token (will not be shown). Press Enter when done."
$sec = Read-Host -AsSecureString "GIT_TOKEN"
$token = Convert-SecureStringToPlainText -secureString $sec
if ([string]::IsNullOrWhiteSpace($token)) {
    Write-Host "No token provided. Exiting without changing .env." -ForegroundColor Yellow
    exit 1
}

$envFile = Join-Path -Path (Get-Location) -ChildPath ".env"
if (Test-Path $envFile) {
    $bak = "$envFile.bak.$((Get-Date).ToString('yyyyMMddHHmmss'))"
    Copy-Item $envFile $bak
    Write-Host "Existing .env backed up to: $bak"
}

# Read existing keys if present, else default
$template = @{}
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^(\s*#)|(^\s*$)') { return }
        $parts = $_ -split '=',2
        if ($parts.Count -eq 2) { $template[$parts[0].Trim()] = $parts[1].Trim() }
    }
}

if (-not $template.ContainsKey('GIT_REPO_URL')) { $template['GIT_REPO_URL'] = 'https://github.com/Manuel-bitcode/movie-bff.git' }
if (-not $template.ContainsKey('MULTIBRANCH_JOB_NAME')) { $template['MULTIBRANCH_JOB_NAME'] = 'movie-bff-multibranch' }
if (-not $template.ContainsKey('PERIODIC_SCAN_SPEC')) { $template['PERIODIC_SCAN_SPEC'] = 'H/5 * * * *' }

$content = @()
$content += "# Generated by scripts/apply-git-token-and-restart.ps1 -- DO NOT COMMIT"
$content += "GIT_TOKEN=$token"
$content += "GIT_REPO_URL=$($template['GIT_REPO_URL'])"
$content += "MULTIBRANCH_JOB_NAME=$($template['MULTIBRANCH_JOB_NAME'])"
$content += "PERIODIC_SCAN_SPEC=$($template['PERIODIC_SCAN_SPEC'])"

Set-Content -Path $envFile -Value $content -Encoding UTF8
Write-Host ".env written to $envFile" -ForegroundColor Green

Write-Host "Bringing Jenkins up (docker-compose will build and restart the jenkins service)..."
try {
    docker-compose up -d --build jenkins
    Write-Host "docker-compose ran. Follow logs with: docker-compose logs -f jenkins" -ForegroundColor Green
} catch {
    Write-Host "Failed to run docker-compose. Ensure Docker and docker-compose are available and you have permissions." -ForegroundColor Red
    Write-Host $_.Exception.Message
    exit 2
}

Write-Host "Done. Jenkins will run with the provided token and init scripts will use it to create credentials if required." -ForegroundColor Green
